export const avalonLocations = [
  {
    id: "waterloo",
    label: "Waterloo",
    title: "University of Waterloo",
    description: "The main anchor for school, research, coursework, and projects built around Waterloo.",
    lat: 43.4723,
    lon: -80.5449,
    action: "select-location",
  },
  {
    id: "montreal",
    label: "Montreal",
    title: "Montreal",
    description: "A city marker ready to connect to future projects, writing, or personal milestones.",
    lat: 45.5019,
    lon: -73.5674,
    action: "select-location",
  },
  {
    id: "san-francisco",
    label: "SF",
    title: "San Francisco",
    description: "A West Coast marker for software, startups, hardware, and other future project clusters.",
    lat: 37.7749,
    lon: -122.4194,
    action: "select-location",
  },
  {
    id: "tokyo",
    label: "Tokyo",
    title: "Tokyo",
    description: "A Tokyo marker for future work, travel, inspiration, or interactive scene branches.",
    lat: 35.6764,
    lon: 139.65,
    action: "select-location",
  },
];
